### ISSUE TITLE
nyari nissan, cuman muncul yang "nissan". yang "Nissan" kagak muncul 

### ISSUE THREAD

**Issue by amarkng** [KStarID/Tubes_ABP#16]
![image](https://github.com/KStarID/Tubes_ABP/assets/88663800/6703eb64-1607-46f7-81d6-36eca431bebd)

**Comment by KStarID** [comment]
karena di database cuman ada nissan

**Comment by amarkng** [comment]
ada nissan silvia ni 
![image](https://github.com/KStarID/Tubes_ABP/assets/88663800/db3db845-9ef1-4b1d-a7b8-b649bd6c7ca8)

**Comment by KStarID** [comment]
liat details merknya apa

**Comment by KStarID** [comment]
ya kalo mau merk pake dropdown berati biar sama semua

**Comment by amarkng** [comment]
udah bisa nih, ada di ubah di func search homecontroller 
![image](https://github.com/KStarID/Tubes_ABP/assets/88663800/d5c59e48-d67a-4abd-ac12-af728c0e9534)

**Comment by KStarID** [comment]
siip, kelazz

**Comment by amarkng** [comment]
issue closed hehe
